# Generated by Django 4.2.1 on 2023-07-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('nom_article', models.CharField(max_length=255)),
                ('section_article', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=255)),
            ],
        ),
    ]
