# Generated by Django 4.2.1 on 2023-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('num_carte_banq', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
                ('code_autorisation', models.CharField(max_length=255)),
            ],
        ),
    ]
